version: '3.3'

services:
  nginx:
    container_name: jirhub_nginx
    image: nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/symfony.conf:/etc/nginx/conf.d/default.conf:ro

  php:
    container_name: jirhub_php
    build: .
    volumes:
      - ./:/var/www/html
      - ./docker/php/symfony.ini:/usr/local/etc/php/conf.d/symfony.ini:ro
